
### 💡💡💡 UTILIZZARE https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### 1. Authenticazione con SSO (Oauth2)
@authzRealm=https://auth.wlms.iad2.click/realms/iad-partner-banks
@clientId=application
@clientSecret=mwRgiAaYfXS16VBoOEwqMdGFthTUHRGG

@username=fantocci
@password=xxx
# Required scopes
@oidcScopes=openid

### Vars
@accessToken={{auth.response.body.access_token}}
@idToken={{auth.response.body.id_token}}

@refreshToken={{auth.response.body.refresh_token}}

### 2. Configurazione delle API

### Richiesta Access & Refresh Token
# @name auth
POST {{authzRealm}}/protocol/openid-connect/token HTTP/1.1
Authorization: Basic {{clientId}} {{clientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope={{oidcScopes}}&username={{username}}&password={{password}}

### (Opts) Refresh del token
# @name refreshAuth
POST {{authzRealm}}/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientId}} {{clientSecret}}

grant_type=refresh_token
&refresh_token={{refreshToken}}

### (Opts) Introspect Token
POST {{authzRealm}}/protocol/openid-connect/token/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientId}} {{clientSecret}}

token={{accessToken}}


###
# @name jwt
GET http://fantocci.lo.iad2.cloud:3000/oidc/jwt HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###
# @name jwt
GET http://fantocci.lo.iad2.cloud:3000/oidc/jwt HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{idToken}}
###
# @name userinfo
GET http://fantocci.lo.iad2.cloud:3000/oidc/userinfo HTTP/1.1
Content-Type: application/json
x-auth-token: {{accessToken}}




